### ISSUE TITLE
WPF Binding "HasChanges"

### ISSUE THREAD

**Issue by Franklin89** [mfidemraizer/trackerdog#20]
Hi

First off nice work with this library.

I am wondering if it is possible to bind to a Property that will tell me if there are changes on a object so that it could be displayed in the UI?

Example:
Got an object "User" on a TabItem and I want to show a * or any symbol if the Object "HasChanges"

Thanks for any hint

**Comment by mfidemraizer** [comment]
First of all, thank you for your good comments ;)

About your issue, it seems like it should be possible. 

I'm thinking about defining a property like this:

`public virtual bool HasChanged { get; set; }`

So, you class constructor could subscribe to `IObjectChangeTracker.Changed` event to set `HasChanged` property:

```
public class User
{
        public User()
        {
                this.GetObjectChangeTracker().Changed += (sender, e) => HasChanged = true;
        }

        // IMPORTANT! IT SHOULD BE VIRTUAL TO LET TRACKERDOG TRACK ITS CHANGES
       public virtual bool HasChanged { get; set; }
}
```

Since `User` will be a proxy during run-time, and it'll automatically implement `INotifyPropertyChanged` it should be enough to define a binding to show an asterisk `*` once an `User` has been changed!

My advise is you should define a _DTO_ and avoid polluting/coupling your domain objects with change-tracking specific operations. 

Let me know if it worked! I'm not an WPF expert, but I believe that this should be an elegant way of fulfilling your requirement :)

## Update

Maybe you might also implement the same approach but from outside of `User`:

```
public class User
{
        // IMPORTANT! IT SHOULD BE VIRTUAL TO LET TRACKERDOG TRACK ITS CHANGES
       public virtual bool HasChanged { get; set; }
}
```

And somewhere in your _view model_ you can still subscribe to `IObjectChangeTracker.Changed` event:

```
// Before binding your users to the UI...
foreach(User user in users)
{
         user.GetObjectChangeTracker().Changed += (sender, e) => user.HasChanged = true;
}
```

That is, you avoid coupling your POCO or domain object to change-tracking details.

**Comment by mfidemraizer** [comment]
Since this question was made on november 2016 and I've seen any activity here, I close this issue for now. If you feel that you want to continue the discussion, feel free to re-open it!
