### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by ordinaryorange** [mfidemraizer/trackerdog#3]
Basic POCO entity with properties.
Added POCO type to TrackerConfiguration as per docs.
Then call On AsTrackable() extension method and get IndexOutOfRangeException.
If comment out the byte[] property, then the exception disappears.
Using Ver 1.1.3 from NuGet

**Comment by mfidemraizer** [comment]
So you've implemented a POCO where one or more properties are *arrays* like `byte[]`:

```
public class A 
{
     public string Text { get; set; }
     public byte[] Buffer { get; set; }
}
```

Is the above code sample your secenario?

**Comment by ordinaryorange** [comment]
Plain stings dont seem to cause the problem.
Only arrary. eg byte[] or string[] properties
Error occurs irrespective of the property being marked as virtual.

Looking forward to getting these resolved as TrackerDog is EXACTLY what I was looking for (even down to the use of Castle...)

**Comment by mfidemraizer** [comment]
I could find the source of the problem.

It's because arrays still implement `IList<T>` and currently TrackerDog detects if a type is trackable based on checking if it's a collection. 

I believe that the best solution here is just skipping arrays, because even when arrays can be casted as collection interfaces, it's hard to track them, since there's no array interface...

My solution (already) has been skipping properties of type `Array` (i.e. AnyType[]). They can be still tracked as regular properties: if you set them, TrackerDog will detect the whole change, but if you change an index within an array, it won't be able to track it...

For now, I'll consider that this issue has been fixed and I'll try to find a way to track changes on array indexes... But this is another story, isn't it? ;)

**Comment by mfidemraizer** [comment]
I've already pushed a new NuGet package: 1.1.4! Will you update your solution and check if this solves your issues? Thanks!

**Comment by ordinaryorange** [comment]
Yep, so far so good. Ran some tests and TrackerDog is running as expected. Nice work on the library.
Ignoring arrays for now wont affect anything I'm doing. The only initial ideas I have to attack the array problem would be some form of Duck typing maybe ?
Thanks for your help.

**Comment by mfidemraizer** [comment]
@ordinaryorange uhm... I believe that what should work is implementing an interface that defines array-specific methods to proxy actual ones. It shouldn't be hard to go this route but I preferred prioritize solving your issues without introducing to munch code because such feature would need more testing.

Well, I'm glad you got what you need in your project and thanks for your good comments about TrackerDog!!

If you find any new issue or you need a new feature or capability just open a new issue!

Thank you!😉
