### ISSUE TITLE
Creating objects

### ISSUE THREAD

**Issue by johnamcruz** [mfidemraizer/trackerdog#34]
Is there a way to create trackable objects without using the object factory? I am building an SDK and will be using trackerdog internally. My problem is that if the users of my SDK creates the object without using the object factory then it will not work. Any idea?

**Comment by mfidemraizer** [comment]
Hey, thank you in advance for using TrackerDog.

Let me try to understand your concern. 

> My problem is that if the users of my SDK creates the object without using the object factory then it will not work

What do you mean? That *object factory* is your own one on your SDK? You mean that someone can reference TrackerDog, create trackable objects and then try to plug them into your SDK flow, right?

Is this your concern? Let me know if I'm in the right track...

**Comment by mfidemraizer** [comment]
I've double-checked your concern and maybe you don't know how to check that a given object is a *trackable object*. 

Your SDK should encapsulate and abstract TrackerDog's `TrackableObjectFactory`, and wherever you need a *trackable object* you should check if a given object implements `IChangeTrackableObject` interface.

Let's put an example:

```c#
public void DoStuff(Person person)
{
     if(!(person is IChangeTrackableObject)) 
     {
           throw new ArgumentException("person", "Given object must be change-trackable");
     }
}
```

Is this the problem you want to solve?

**Comment by johnamcruz** [comment]
My concern is the call below

`App app = trackableObjectFactory.CreateOf<App>();`
`app.Users.Add(new User { Name = "Matías", Age = 30 });`

it would be awesome if I can somehow instatiate a trackable object using
`var app = new App();`

**Comment by mfidemraizer** [comment]
This is impossible unless I would implement some C# extension through Roslyn, and it wouldn't be the official C# implementation anymore...

BTW, what's the issue behind the scenes? Check my previous comment and let me know if this is the core problem.

**Comment by johnamcruz** [comment]
No issues. I love tracker dog. I ended up just wrapping the trackableqbject factory as a method AsTrackable() that returns the object

`var trackableApp = app.AsTrackable();`

**Comment by mfidemraizer** [comment]
Well, believe or not, TrackerDog 1.x had an extension method called exactly like yours, but I had to refactor the lib to be *dependency injection-friendly*. 

I suggest that you should go the DI way instead of your current approach, because you won't be able to mock TrackerDog for testing purposes. 

Maybe you could define your own trackable object factory interface and inject its implementation wherever you want:

```c#
public class A
{
     public A(ITrackableFactory trackableFactory)
     {
             TrackableFactory = trackableFactory;
     }

     private ITrackableFactory TrackableFactory { get; }

     public void DoStuff()
     {
            App app = TrackableFactory.CreateOf<App>();
app.Users.Add(new User { Name = "Matías", Age = 30 });
     }
}
```

That way, you get an added value: you can do stuff before and after creating a trackable object in your SDK., and your SDK consumers won't need to use TrackerDog's `ITrackableObjectFactory` interface (you avoid coupling your consumer's code to TrackerDog).

What do you think about this approach?

**Comment by johnamcruz** [comment]
That works great. I like using DI.
