### ISSUE TITLE
Object cannot be converted

### ISSUE THREAD

**Issue by markgould** [mfidemraizer/trackerdog#39]
Not sure if I'm doing something wrong here but I get an error when tracking an object that has a List<string> is this not supported?

> Object of type 'Castle.Proxies.IList\`1Proxy' cannot be converted to type' System.Collections.Generic.List\`1[System.String]'

Here is a simple repro: https://gist.github.com/markgould/cbce26c699a003bc4a4fdb16e4d2c0f9

**Comment by markgould** [comment]
It looks like I just had to change it to IList. It wasn't immediately clear from the documentation, but now it seems to work!

**Comment by mfidemraizer** [comment]
@markgould Hey! Thank you for using TrackerDog.

Right, you're forced to use interfaces. Anyway, you may use `IList<T>` instead of `IList`.

BTW, it seems like I've been not absolutely clear about that fact, while you'll find this statement [here](http://matiasfidemraizer.com/trackerdog/html/1e03762d-b9f5-44af-a4b0-c23c36064c24.htm): 

>  Actually, TrackerDog doesn't track any type of collection, but you must tell it to track certain collection types. TrackerDogConfiguration.CollectionConfiguration let's you customize which collection interfaces can be tracked on and what implementations should be instantiated and proxied to track their changes.
> 
> These are the default implementations provided out-of-the-box:
> 
>     ISet<T> implemented by HashSet<T>
>     IList<T> implemented by List<T>
>     ICollection<T> implemented by List<T>
>     IEnumerable<T> implemented by List<T>

Probably I should update the docs both in how collection change tracking works and in *how-tos* to be clear about this.

So is it working already for you? ;)

**Comment by markgould** [comment]
Yes, it's working great now, thanks!

**Comment by mfidemraizer** [comment]
@markgould Nice! I close the issue. If you find any other issue or doubt, feel free to open a new one :)
